#!/bin/sh /etc/rc.common
# File: /etc/init.d/EAPD

START=98
EXTRA_COMMANDS="L"
EXTRA_HELP="        L   Learning Mode"

error() {
        echo "${initscript}:" "$@" 1>&2
}

start() {
        echo "EvilAPDefender (EAPD) Daemon - Protect your Wireless Network from Bad Access Points."
        echo "Author: Shant Patrick Tchatalbachian."
        echo "GNU License v3"
        echo " "
        echo "Starting MySQL..."
        echo "Starting MySQL at $(date -u)" >> /root/EvilAPDefender.log
        /etc/init.d/mysqld start
        sleep 5
        echo "Pausing Networking..."
        echo "Pausing Networking at $(date -u)" >> /root/EvilAPDefender.log
        /etc/init.d/network stop
        sleep 5
        echo "Starting Scan Please Wait..."
        echo "Starting Scan at $(date -u)" >> /root/EvilAPDefender.log
        python /root/EvilAPDefender.py -N | tee -a /root/EvilAPDefender.log
        echo "Scan Complete."
        echo "Scan Complete at $(date -u)" >> /root/EvilAPDefender.log
        /etc/init.d/mysqld stop
        sleep 5
        echo "Stopped MySQL."
        echo "Stopped MySQL at $(date -u)" >> /root/EvilAPDefender.log
        /etc/init.d/network start
        sleep 5
        echo "Network Resumed."
        echo "Network Resumed at $(date -u)" >> /root/EvilAPDefender.log
        sleep 5
        echo "|-------------------------------------------END-------------------------------------------|" >> /root/EvilAPDefender.log
}

stop() {
        pkill -f "python /root/EvilAPDefender.py -N"
        pkill -f "python /root/EvilAPDefender.py -L"
        echo "Aborted Scan."
        echo "Aborted Scan at $(date -u)" >> /root/EvilAPDefender.log
}

L() {
        echo "EvilAPDefender (EAPD) Learning Mode - Protect your Wireless Network from Bad Access Points."
        echo "Author: Shant Patrick Tchatalbachian."
        echo "GNU License v3"
        echo " "
        echo "Starting MySQL..."
        echo "Starting MySQL at $(date -u)" >> /root/EvilAPDefender.log
        /etc/init.d/mysqld start
        sleep 5
        echo "Pausing Networking..."
        echo "Pausing Networking at $(date -u)" >> /root/EvilAPDefender.log
        /etc/init.d/network stop
        sleep 5
        echo "Started Learning Mode Please Wait..."
        echo "Learning Mode Run at $(date -u)" >> /root/EvilAPDefender.log
        python /root/EvilAPDefender.py -L
        echo "Learning Mode Complete."
        echo "Learning Mode Complete at $(date -u)" >> /root/EvilAPDefender.log
        /etc/init.d/mysqld stop
        sleep 5
        echo "Stopped MySQL."
        echo "Stopped MySQL at $(date -u)" >> /root/EvilAPDefender.log
        /etc/init.d/network start
        sleep 5
        echo "Network Resumed."
        echo "Network Resumed at $(date -u)" >> /root/EvilAPDefender.log
        sleep 5
        echo "|-------------------------------------------END-------------------------------------------|" >> /root/EvilAPDefender.log
}
