#!/bin/sh /etc/rc.common
# File: /etc/init.d/mysqld

START=95
STOP=10


error() {
	echo "${initscript}:" "$@" 1>&2
}

start() {
	/usr/bin/mysqld --skip-grant-tables &
}

stop() {
	pkill -f "/usr/bin/mysqld --skip-grant-tables"
}
