#!/bin/sh /etc/rc.common
# File: /etc/init.d/eapdd

######################################################################
#
# Copyright (C) 2020 Shant Patrick Tchatalbachian
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
######################################################################

EXTRA_COMMANDS="L H"
EXTRA_HELP="        L       Learning Mode
        H       Help"

error() {
        echo "${initscript}:" "$@" 1>&2
}

start() {
        echo "Evil Access Point Defender - Daemon (EAPDD) - Protect your Wireless Network from Bad Access Points."
        echo "Author: Shant Patrick Tchatalbachian." && echo "GNU License v3"
        echo " " && echo "Scanning Mode." && echo "Scanning Mode" >> /root/eapd.log && echo " "
        echo "Starting MySQL..." && echo " " && echo "Starting MySQL at $(date '+%r on %x')" >> /root/eapd.log
        /etc/init.d/mysqld start && sleep 5
        echo "Starting Scan Please Wait..." && echo " " && echo "Starting Scan at $(date '+%r on %x')" >> /root/eapd.log
        python /root/eapd.py -N
        echo " " && echo "Scan Complete." && echo " " && echo "Scan Complete at $(date '+%r on %x')" >> /root/eapd.log
        /etc/init.d/mysqld stop && sleep 5
        echo "Stopped MySQL." && echo " " && echo "Stopped MySQL at $(date '+%r on %x')" >> /root/eapd.log
        echo "Log file saved to /root/eapd.log." && echo " "
        fail="$(cat /tmp/fail)"
        if [ "$fail" == "Yes" ]; then
                echo "EAPD Fail at $(date '+%r on %x')!!! Check Log!" >> /tmp/auth	
                C2EXFIL STRING /tmp/auth FAIL
                C2EXFIL STRING /root/eapd.log FAIL_LOG
                wget -q -s "https://cronitor.link/YOUR_AUTHLINK_HERE/fail?auth_key=YOUR_AUTH_KEY_HERE&msg=EAPD"
        fi
        echo "|-------------------------------------------END-------------------------------------------|" >> /root/eapd.log
}

stop() {
        pkill -f "python /root/eapd.py -N" && pkill -f "python /root/eapd.py -L" && /etc/init.d/mysqld stop
        echo "Aborted Scan." && echo " " && echo "Aborted Scan, Moved Log, or Reboot at $(date '+%r on %x')" >> /root/eapd.log
        echo "Log file saved to /root/eapd.log." && echo " "
        echo "|-------------------------------------------END-------------------------------------------|" >> /root/eapd.log
}

L() {
        echo "Evil Access Point Defender - Daemon (EAPDD) - Protect your Wireless Network from Bad Access Points."
        echo "Author: Shant Patrick Tchatalbachian." && echo "GNU License v3"
        echo " " && echo "Learning Mode." && echo "Learning Mode" >> /root/eapd.log && echo " "
        echo "Stopping Cron..." && echo " " && echo "Stopping Cron at $(date '+%r on %x')" >> /root/eapd.log
        /etc/init.d/cron stop && sleep 5
        echo "Stopping Any Running Scans..." && echo " " && echo "Stopping Any Running Scans at $(date '+%r on %x')" >> /root/eapd.log
        pkill -f "python /root/eapd.py -N" && sleep 10
        echo "Starting MySQL..." && echo " " && echo "Starting MySQL at $(date '+%r on %x')" >> /root/eapd.log
        /etc/init.d/mysqld start && sleep 5
        echo "Starting Learning Mode Please Wait..." && echo " " && echo "Starting Learning Mode at $(date '+%r on %x')" >> /root/eapd.log
        python /root/eapd.py -L
        echo " " && echo "Learning Mode Complete." && echo " " && echo "Learning Mode Complete at $(date '+%r on %x')" >> /root/eapd.log
        /etc/init.d/mysqld stop && sleep 5
        echo "Stopped MySQL." && echo " " && echo "Stopped MySQL at $(date '+%r on %x')" >> /root/eapd.log
        echo "Log file saved to /root/eapd.log." && echo " "
        echo "Start Scheduled Scans by Running '/etc/init.d/cron enable && reboot'." && echo " "
        echo "|-------------------------------------------END-------------------------------------------|" >> /root/eapd.log
}

H() {
        echo "Evil Access Point Defender - Daemon (EAPDD) - Protect your Wireless Network from Bad Access Points."
        echo "Author: Shant Patrick Tchatalbachian." && echo "GNU License v3"
        echo " " && echo "Runs Daemonized on OpenWrt 15.x and above."
        echo " " && echo "Check out the Wiki: https://github.com/0mniteck/EAPD/wiki/Wiki"
        echo " " && echo "Just run '/etc/init.d/eapdd L' to start learning mode."
        echo " " && echo "Start Scheduled Scans by Running '/etc/init.d/cron enable && reboot'." && echo " "
}
