#!/bin/sh /etc/rc.common
# File: /etc/init.d/mysqld

######################################################################
#
# Copyright (C) 2019 Shant Patrick Tchatalbachian
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
######################################################################

error() {
	echo "${initscript}:" "$@" 1>&2
}

start() {
	mkdir /var/log/mysql/ && chmod 777 /var/log/mysql/
	mkdir /var/log/mysqld/ && chmod 777 /var/log/mysqld/
	mkdir /var/run/mysqld/ && chmod 777 /var/run/mysqld/
	/usr/bin/mysqld --skip-grant-tables &
}

stop() {
	pkill -f "/usr/bin/mysqld --skip-grant-tables"
}
