#!/bin/sh /etc/rc.common
# File: /etc/init.d/mysqld

START=95
STOP=1


error() {
	echo "${initscript}:" "$@" 1>&2
}

start() {
	mkdir /var/run/mysqld/ && chmod 777 /var/run/mysqld/
	/usr/bin/mysqld --skip-grant-tables &
}

stop() {
	pkill -f "/usr/bin/mysqld --skip-grant-tables"
}
